name: Publish Artifacts on Release

on:
  release:
    types: [created]

env:
  PGP_PASSPHRASE: ${{ secrets.GH_ACTIONS_BOT_PGP_PASSPHRASE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
          gpg-private-key: ${{ secrets.GH_ACTIONS_BOT_PGP_SECRET }}
      - name: Publish ${{ github.ref }}
        run: sbt publishSigned
